config/routes.rb
Rails.application.routes.draw do
  
  resources :topics

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'

  get 'pages/discussion'

  resources :schedules
  resources :players
  
  mount ActionCable.server => '/cable'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  validates_presence_of :title

  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all  
  end

  def show
    @comment = Comment.new
    @topic = Topic.includes(:comments).find(params[:id])
    
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id 
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title, :subtitle, :body)
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 50
  end
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |f| %>

  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 10, placeholder: 'Content' %>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="container">

  <h2>Edit Topic</h2>

  <%= render 'form', topic: @topic %>

  <%= link_to 'Show', @topic, class: 'btn btn-light' %> |
  <%= link_to 'Back', topics_path, class: 'btn btn-light' %> |
  <%= link_to 'Delete', @topic, class: 'btn btn-light', method: :delete, data: {confirm: 'Are you sure?'} %>
  
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="card topic-card">
    <div class="row">
      <div class="col-md-8">
        <div class="card-body">
          <h2 class="card-title">Welcome to the Discussion page.</h2>
          <% if !current_user.is_a? GuestUser %>
            <h3 class="card-text">Join in on an ongoing discussion or start your own here</h3>
            <%= link_to "New Topic", new_topic_url, class: 'btn btn-secondary btn-block' %>
          <% else %>
            <h3 class="card-text">Sign in or sign up to start a new conversation.</h3>
          <% end %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="text-center topic-image">
          <%= image_tag 'yankee_logo.gif', width: '75%' %>
        </div>
      </div>
    </div>
  </div>
  <div>
    <% @topics.each do |t| %>
      
      <div class="row">
        <div class="col-md-6">
          <div class='card topic-card'>
            <h4><%= link_to t.title, t %></h4>
            <h5><%= t.subtitle %></h5>
            <div>
              <small>Posted by: <%= t.user.first_name %> <%= distance_of_time_in_words(t.created_at, Time.now) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <hr />
    <%= link_to 'Back', root_path, class: 'btn btn-light' %>
  </div>
  
</div>

app/views/topics/new.html.erb
<div class="container">
  <h2>New Topic</h2>

  <%= render 'form', topic: @topic %>

  <%= link_to 'Back', topics_path, class: 'btn btn-light' %>
  
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 top-marg">
      <div class="jumbotron">
        <h2 class="display-4"><%= @topic.title %></h2>
        <h4 class="lead"><%= @topic.subtitle %></h4>
        <hr class="my-4">
        <p><%= @topic.body %></p>
      </div>


      <hr />

      <% if !current_user.is_a? GuestUser %>
        <%= render 'comments/comment_form' %>
      <% end %>

      <div id="comments" data-topic-id="<%= @topic.id %>" >
        <%= render @topic.comments %>
      </div>
      <div class="topic-card">
        <% if @topic.user_id == current_user.id || current_user.role == :admin %>   
          <%= link_to 'Edit', edit_topic_path(@topic), class: 'btn btn-light' %> |
          <%= link_to 'Back', topics_path, class: 'btn btn-light' %> | <%= link_to 'Delete', @topic, class: 'btn btn-light', method: :delete, data: {confirm: 'Are you sure?'} %>
        <% else %>
          <%= link_to 'Back', topics_path, class: 'btn btn-light' %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="text-center show-logo">
        <%= image_tag 'yankee_logo.gif', width: '75%' %>
      </div>
    </div>
  </div>
</div>