config/routes.rb
Rails.application.routes.draw do
  
  resources :topics

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'

  get 'pages/discussion'

  resources :schedules
  resources :players
  
  mount ActionCable.server => '/cable'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  validates_presence_of :title

  has_many :games
  accepts_nested_attributes_for :games,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['opponent'].blank? }
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @grid = initialize_grid(Schedule)
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.user_id = current_user.id 

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:title, games_attributes: [:id, :opponent, :game_date, :location, :result, :_destroy])
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<div class="container top-marg">
  <div class="row"
    <div class="col-md-8">
      <%= form_with(model: schedule, local: true) do |f| %>
        <% if schedule.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

            <ul>
            <% schedule.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <h3>Schedule:</h3>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, id: :schedule_title, class: 'form-control' %>
        </div>
        <hr />
        <br />
        <div>
          <h3>Games:</h3>
          <div>
            <%= f.fields_for :games do |g| %>
              <%= render 'game_fields', f: g %>
            <% end %>

            <div>
              <%= link_to_add_association 'Add Game', f, :games, class: 'btn btn-info btn-sm' %>
            </div>
          </div>
        </div>

        <div class="form-group top-marg">
          <%= f.submit 'Save Form', class: 'btn btn-primary btn-block', width: '75%' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/schedules/_game_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :opponent %>
  <%= f.text_field :opponent, class: 'form-control' %>

  <%= f.label :date %>
  <%= f.date_field :game_date, class: 'form-control' %>

  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control' %>

  <%= f.label :result %>
  <%= f.text_field :result, class: 'form-control' %>

  <%= link_to_remove_association 'Remove Game', f, class: 'btn btn-warning btn-sm' %>
</div>

app/views/schedules/edit.html.erb
<div class="container">
  <h1>Editing Schedule</h1>

  <%= render 'form', schedule: @schedule %>

  <%= link_to 'Show', @schedule, class: 'btn btn-light' %> |
  <%= link_to 'Back', schedules_path, class: 'btn btn-light' %>
</div>

app/views/schedules/index.html.erb
<div class="container">

  <h1>Schedules</h1>

  <br>
  <div class="row">
    <div class="col-md-8">
      <% @schedules.each do |schedule| %>
        <div class="card sched-title">
          <div class="row">
            <div class="col-md-8">
              <h3><%= link_to schedule.title, schedule %></h3>
            </div>
            <div class="col-md-4">
              <%= link_to 'Edit', edit_schedule_path(schedule), class: 'btn btn-light' %> |
              <%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <br />
  <hr />

  <%= link_to 'New Schedule', new_schedule_path, class: 'btn btn-light' %>
</div>

app/views/schedules/new.html.erb
<div class="container">
  <h1>New Schedule</h1>

  <%= render 'form', schedule: @schedule %>

  <%= link_to 'Back', schedules_path, class: 'btn btn-light' %>
</div>

app/views/schedules/show.html.erb
<div class="container">
  <div class="top-marg">
    <div class="row">
      <div class="col-md-9">
        <div class='jumbotron'>
          <div class="row">
            <div class="col-md-5">
              <h1><%= @schedule.title %></h1>
            </div>
            <div class="col-md-7 text-right">
              <h1 class="record-title">10 - 0</h1>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="text-center">
          <%= image_tag 'yankee_logo.gif', width: '75%' %>
        </div>
      </div>
  </div>
  <br />
  <hr />
  <br />

  <div class="row featurette">
    <div class="col-md-7">
      <% @schedule.games.each do |g| %>
        <div class="row">
          <div class="col-md-8">
            <h3><%= g.opponent %></h3>
          </div>
          <div class="col-md-4">
            <p class="lead"><%= g.game_date %></p>
            <p><%= g.location %></p>
            <p><%= g.result %></p>
          </div>
        </div><br />
        <hr class="my-4">

      <% end %>
    </div>
  </div>
  <div class="topic-card">
    <% if current_user.role == :admin %>
      <%= link_to 'Edit', edit_schedule_path(@schedule), class: 'btn btn-light' %> |
      <%= link_to 'Back', schedules_path, class: 'btn btn-light' %>
    <% else %>
      <%= link_to 'Back', root_path, class: 'btn btn-light' %>
    <% end %>
  </div>
</div>
<hr class="featurette-divider">