config/routes.rb
Rails.application.routes.draw do
  
  resources :topics

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'

  get 'pages/discussion'

  resources :schedules
  resources :players
  
  mount ActionCable.server => '/cable'
end

app/views/shared/_footer.html.erb
<footer class="container foot-cont">
  <p class="float-right"><a href="#" class="btn">Back to top</a></p>
  <p>&copy; 2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to 'Yankees', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Discussion', topics_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Roster', players_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Schedule', schedule_path(1), class: 'nav-link' %>
      </li>
      <% if !current_user.is_a? GuestUser %>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit', edit_user_registration_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Signup', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if current_user.role == :admin %>
        <li class="nav-item">
          <%= link_to 'New Team and Schedule', schedules_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <% if !current_user.is_a? GuestUser %>
      <div class="welcome text-right">Welcome, <%= current_user.first_name %></div>
    <% end %>
  </div>
</nav>